name: photo_clean_core
description: "Minimal core: perceptual hash + blur + streaming duplicate detection."
version: 0.1.0
repository: https://github.com/xiangj1/clean-tool-package
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  image: ^4.2.0
dev_dependencies:
  test: ^1.24.0
