name: photo_clean_core
description: Core perceptual hash and clustering utilities for Photo Clean.
version: 0.1.0
publish_to: none
resolution: workspace
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  image: ^4.2.0
  collection: ^1.18.0
dev_dependencies:
  test: ^1.24.0
