name: photo_clean_cli
description: Command-line interface for Photo Clean.
version: 0.1.0
publish_to: none
resolution: workspace
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  image: ^4.2.0
  path: ^1.9.0
  photo_clean_core:
    path: ../photo_clean_core
  args: ^2.5.0
dev_dependencies:
  test: ^1.24.0
